### ISSUE TITLE
进入文章页面时候，页面会闪烁

### ISSUE THREAD

**Issue by DualWield** [hilongjw/vue-material-blog#3]
先小小的缩小一下， 然后回复原位

**Comment by hilongjw** [comment]
这个原因应该是在调用material design lite的方法来渲染页面时导致的，我打算加上一个loading page来处理这里的切换，就是当渲染完成之后再切入文章页面。

**Comment by DualWield** [comment]
确定问题可以把这个issue关了

**Comment by hilongjw** [comment]
ok
